import { defineConfig, devices } from '@playwright/test';
import { generatedPreviewEnv } from './tooling/lib/generated-preview.mjs';

// A host that already has a Chromium should not have to fetch another.
const launchOptions = { executablePath: process.env.APP_BUILDER_BROWSER_EXECUTABLE };

// The application-journey benchmark project, generated by
// `npm run generate:acceptance` and served by its own dev script. This lane
// exists to prove that what the database enforces is what a person actually
// experiences, so it runs against the generated repository rather than against
// the factory.
//
// It is the canonical B2B SaaS project plus `scheduled-decisions` — a strict
// superset, which is why the records, files, notifications and administration
// journeys still run here unchanged. One project rather than two because a
// second one would mean a second `npm install` and a second dev server to prove
// the same tenancy twice; the b2b-saas project is still generated and still held
// to its own launch-readiness ceiling, it is simply not the one served.
const GENERATED = '.tmp/generated-acceptance-journey-benchmark';

// Supplied by whatever started the Supabase stack.
//
// Checked in the server command rather than at module load. Throwing here would
// be louder but would also make this file unreadable to anything that merely
// imports it — the harness audit that reads every Playwright config to check it
// honours each generated project's declared preview environment does exactly
// that, and a config that cannot be inspected is a config nothing can hold to a
// contract. The failure stays loud and stays early: the dev server refuses to
// start, and says which variable is missing.
const supabaseUrl = process.env.VITE_SUPABASE_URL ?? '';
const supabaseKey = process.env.VITE_SUPABASE_PUBLISHABLE_KEY ?? '';
const requireStack = 'if [ -z "$VITE_SUPABASE_URL" ] || [ -z "$VITE_SUPABASE_PUBLISHABLE_KEY" ]; then'
  + ' echo "The generated-application journey needs VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY for the stack it should run against." >&2; exit 1; fi;';

// Where this lane leaves the material an independent reviewer reads. It is
// deliberately outside `test-results`, which Playwright empties at the start of
// every run and fills with per-attempt scratch; a review packet has to survive
// as one directory that can be uploaded, unzipped and read in order.
const EVIDENCE = '.app-builder/generated-app-journey';

export default defineConfig({
  testDir: './tests/generated-app',
  fullyParallel: false,
  retries: process.env.CI ? 1 : 0,
  workers: 1,
  // A machine-readable result beside the human one. Before this the lane
  // reported to a terminal and nowhere else, so a green run left no record of
  // what ran — and `npm run evidence:generated-app` has nothing to read from a
  // wall of text that has already scrolled past.
  reporter: [
    [process.env.CI ? 'line' : 'list'],
    ['json', { outputFile: `${EVIDENCE}/playwright-report.json` }],
  ],
  use: {
    baseURL: 'http://127.0.0.1:4373',
    trace: 'retain-on-failure',
    // `on`, not `only-on-failure`. The stage criterion this lane is held to is
    // that rendered product evidence receives independent review, and under
    // `only-on-failure` a passing run photographs nothing: the evidence step in
    // CI uploaded an empty directory, and the review had no object. A journey
    // that passed is exactly the one worth looking at, because passing its
    // assertions is not the same as looking right.
    screenshot: 'on',
    launchOptions,
  },
  projects: [{ name: 'chromium', use: { ...devices['Desktop Chrome'] } }],
  webServer: {
    command: `${requireStack} npm --prefix ${GENERATED} run dev -- --host 127.0.0.1 --port 4373`,
    env: { ...generatedPreviewEnv(GENERATED), VITE_SUPABASE_URL: supabaseUrl, VITE_SUPABASE_PUBLISHABLE_KEY: supabaseKey },
    url: 'http://127.0.0.1:4373',
    reuseExistingServer: !process.env.CI,
    timeout: 120_000,
    gracefulShutdown: { signal: 'SIGTERM', timeout: 5_000 },
  },
});
