import { defineConfig, devices } from '@playwright/test';
import { generatedPreviewEnv } from './tooling/lib/generated-preview.mjs';
import { lanePort, laneServer, laneUrl } from './tooling/lib/e2e-server.mjs';

// A host that already has a Chromium should not have to fetch another.
const launchOptions = { executablePath: process.env.APP_BUILDER_BROWSER_EXECUTABLE };

// The application-journey benchmark project, generated by
// `npm run generate:acceptance` and served by its own dev script. This lane
// exists to prove that what the database enforces is what a person actually
// experiences, so it runs against the generated repository rather than against
// the factory.
//
// It is the canonical B2B SaaS project plus `scheduled-decisions` — a strict
// superset, which is why the records, files, notifications and administration
// journeys still run here unchanged. One project rather than two because a
// second one would mean a second `npm install` and a second dev server to prove
// the same tenancy twice; the b2b-saas project is still generated and still held
// to its own launch-readiness ceiling, it is simply not the one served.
const GENERATED = '.tmp/generated-acceptance-journey-benchmark';

// Supplied by whatever started the Supabase stack.
//
// Checked in the server command rather than at module load. Throwing here would
// be louder but would also make this file unreadable to anything that merely
// imports it — the harness audit that reads every Playwright config to check it
// honours each generated project's declared preview environment does exactly
// that, and a config that cannot be inspected is a config nothing can hold to a
// contract. The failure stays loud and stays early: the dev server refuses to
// start, and says which variable is missing.
const supabaseUrl = process.env.VITE_SUPABASE_URL ?? '';
const supabaseKey = process.env.VITE_SUPABASE_PUBLISHABLE_KEY ?? '';
const requireStack = 'if [ -z "$VITE_SUPABASE_URL" ] || [ -z "$VITE_SUPABASE_PUBLISHABLE_KEY" ]; then'
  + ' echo "The generated-application journey needs VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY for the stack it should run against." >&2; exit 1; fi;';

// Where this lane leaves the material an independent reviewer reads. It is
// deliberately outside `test-results`, which Playwright empties at the start of
// every run and fills with per-attempt scratch; a review packet has to survive
// as one directory that can be uploaded, unzipped and read in order.
const EVIDENCE = '.app-builder/generated-app-journey';

export default defineConfig({
  testDir: './tests/generated-app',
  fullyParallel: false,
  // Zero, and not because retries are disliked.
  //
  // Every journey here signs in and writes: a record, a file, a notification
  // read-state, a decision. The seed that puts the database in a known state is
  // a CI step that runs once, before Playwright starts, so a second attempt
  // begins wherever the first one stopped. The lane's first instrumented run
  // showed what that costs — the decision journey failed after writing its
  // decision, and the retry went looking for a "submit decision" control the
  // application had correctly replaced with "change decision". That failure was
  // loud. The quiet version is the one to fear: an attempt fails mid-write, the
  // retry runs on top of the result and goes green, and a pass from a state the
  // seed never described is published as evidence the journey works.
  //
  // A retry here would need a deterministic reset to the same named seed before
  // each attempt. Until something provides that, one attempt is the honest
  // number, and `retryViolatesMutation` in the evidence step enforces the rule
  // rather than trusting this line to stay at zero.
  retries: 0,
  workers: 1,
  // A machine-readable result beside the human one. Before this the lane
  // reported to a terminal and nowhere else, so a green run left no record of
  // what ran — and `npm run evidence:generated-app` has nothing to read from a
  // wall of text that has already scrolled past.
  reporter: [
    [process.env.CI ? 'line' : 'list'],
    ['json', { outputFile: `${EVIDENCE}/playwright-report.json` }],
  ],
  use: {
    baseURL: laneUrl('generated-app'),
    trace: 'retain-on-failure',
    // `on`, not `only-on-failure`. The stage criterion this lane is held to is
    // that rendered product evidence receives independent review, and under
    // `only-on-failure` a passing run photographs nothing: the evidence step in
    // CI uploaded an empty directory, and the review had no object. A journey
    // that passed is exactly the one worth looking at, because passing its
    // assertions is not the same as looking right.
    screenshot: 'on',
    launchOptions,
  },
  projects: [{ name: 'chromium', use: { ...devices['Desktop Chrome'] } }],
  // This lane publishes a review packet, so the identity of the server it
  // photographed is part of the claim. It shared 4373 with the accessibility
  // lane and could be answered by any other worktree; now the port is this
  // checkout's and the lane starts the server itself.
  webServer: laneServer({
    lane: 'generated-app',
    command: `${requireStack} npm --prefix ${GENERATED} run dev -- --host 127.0.0.1 --port ${lanePort('generated-app')}`,
    env: { ...generatedPreviewEnv(GENERATED), VITE_SUPABASE_URL: supabaseUrl, VITE_SUPABASE_PUBLISHABLE_KEY: supabaseKey },
  }),
});
