#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';
import process from 'node:process';
import { readJson, validateManifest } from './lib/manifest.mjs';

function arg(name) {
  const i = process.argv.indexOf(name);
  return i >= 0 ? process.argv[i + 1] : undefined;
}

const manifestPath = arg('--manifest');
if (!manifestPath) {
  console.error('Usage: npm run create-app -- --manifest <manifest.json> [--out <directory>]');
  process.exit(2);
}
const manifest = readJson(manifestPath);
const errors = validateManifest(manifest);
if (errors.length) {
  console.error('Refusing to generate from an invalid manifest:');
  errors.forEach((error) => console.error(`- ${error}`));
  process.exit(1);
}

const out = path.resolve(arg('--out') ?? path.join('generated', manifest.project.slug));
if (fs.existsSync(out)) {
  console.error(`Refusing to overwrite existing directory: ${out}`);
  process.exit(1);
}

fs.mkdirSync(path.join(out, '.product'), { recursive: true });
fs.mkdirSync(path.join(out, 'src', 'config'), { recursive: true });
fs.writeFileSync(path.join(out, '.product', 'manifest.json'), JSON.stringify(manifest, null, 2) + '\n');
const enabled = Object.entries(manifest.modules).filter(([, enabled]) => enabled).map(([name]) => name);
fs.writeFileSync(path.join(out, 'src', 'config', 'enabled-modules.json'), JSON.stringify(enabled, null, 2) + '\n');
fs.writeFileSync(path.join(out, 'README.md'), `# ${manifest.project.name}\n\nGenerated by App Builder foundation v0.\n\nPrimary goal: ${manifest.project.primaryGoal}\n\nEnabled modules: ${enabled.join(', ') || 'none'}\n`);
console.log(`Created deterministic v0 project shell: ${out}`);
console.log(`Enabled modules: ${enabled.join(', ') || 'none'}`);
console.log('Note: recipe installation and production app templates are Phase 2 roadmap items.');
